$date = Get-Date -Format "dddd, dd 'de' MMMM 'de' yyyy"
Write-Host "================================================================"
Write-Host "  AGENTE EJECUTIVO ANTIFRAGIL"
Write-Host "  $date"
Write-Host "================================================================"
Write-Host ""
Write-Host "Proyecto : CEO Brief - Chief of Staff Digital"
Write-Host "Usuario  : Fernando Campos (CEO)"
Write-Host "Acceso   : Notion MCP conectado"
Write-Host ""
Write-Host "ARRANQUE AUTOMATICO: PAUSADO por decision de Fernando."
Write-Host "No ejecutar el protocolo de inicio ni el briefing salvo peticion explicita."
Write-Host "Para reactivar: restaurar este bloque y la seccion 'Protocolo de inicio"
Write-Host "de sesion' en .claude/CLAUDE.md."
Write-Host ""
Write-Host "Comandos disponibles:"
Write-Host "  /briefing        - Briefing ejecutivo completo"
Write-Host "  /sprint          - Snapshot rapido del sprint activo"
Write-Host "  /alertas         - Solo alertas criticas"
Write-Host "  /nuevo-sprint    - Apertura/cierre de sprint semanal"
Write-Host "  /publicar-notion - Publica el briefing en Notion para el equipo"
Write-Host ""
Write-Host "================================================================"
