#!/bin/bash
# SessionStart.sh — Agente Ejecutivo de Antifragil
# Proporciona contexto inicial para que Claude arranque directamente con el briefing

echo "================================================================"
echo "  AGENTE EJECUTIVO ANTIFRAGIL"
echo "  $(date '+%A, %d de %B de %Y')"
echo "================================================================"
echo ""
echo "Proyecto : CEO Brief — Chief of Staff Digital"
echo "Usuario  : Fernando Campos (CEO)"
echo "Acceso   : Notion MCP conectado"
echo ""
echo "INSTRUCCION AUTOMATICA:"
echo "Lee SYSTEM_VISION.md y ejecuta el protocolo de inicio"
echo "de sesion definido en .claude/CLAUDE.md (briefing ejecutivo)."
echo ""
echo "Comandos disponibles:"
echo "  /briefing        — Briefing ejecutivo completo"
echo "  /sprint          — Snapshot rapido del sprint activo"
echo "  /alertas         — Solo alertas criticas"
echo "  /nuevo-sprint    — Apertura/cierre de sprint semanal"
echo "  /publicar-notion — Publica el briefing en Notion para el equipo"
echo ""
echo "================================================================"
