$date = Get-Date -Format "dddd, dd 'de' MMMM 'de' yyyy"
Write-Host "================================================================"
Write-Host "  AGENTE EJECUTIVO ANTIFRAGIL"
Write-Host "  $date"
Write-Host "================================================================"
Write-Host ""
Write-Host "Proyecto : CEO Brief - Chief of Staff Digital"
Write-Host "Usuario  : Fernando Campos (CEO)"
Write-Host "Acceso   : Notion MCP conectado"
Write-Host ""
Write-Host "INSTRUCCION AUTOMATICA:"
Write-Host "Lee SYSTEM_VISION.md y ejecuta el protocolo de inicio"
Write-Host "de sesion definido en .claude/CLAUDE.md (briefing ejecutivo)."
Write-Host ""
Write-Host "Comandos disponibles:"
Write-Host "  /briefing        - Briefing ejecutivo completo"
Write-Host "  /sprint          - Snapshot rapido del sprint activo"
Write-Host "  /alertas         - Solo alertas criticas"
Write-Host "  /nuevo-sprint    - Apertura/cierre de sprint semanal"
Write-Host "  /publicar-notion - Publica el briefing en Notion para el equipo"
Write-Host ""
Write-Host "================================================================"
